"""Parser for the 2023 Deutsch Well Obsidian vault (data/deutsch/deutsch-well_2023).

Vault structure (see 'Deutsch Well Style Guide.md' in the vault):
- L1: top-level folders = categories (first-tier concepts), each with an index page
- L2: subfolders whose NAMES are claims (assertions about the category), each with an index page
- L3: excerpt files inside a claim folder; content = '<source file>.md : <verbatim excerpt>' + #L3 tag

Index pages ('Associated Entries' lists, #L1/#L2/#L3 tags) are derived structure and are
not imported — they can be regenerated by a future export-obsidian command."""
import os
import re

WELL_ROOT = "data/deutsch/deutsch-well_2023"
SOURCE_PREFIX_RE = re.compile(r"^(.*?\.md)\s*:\s*(.*)$", re.DOTALL)

def is_image_artifact(file_name, text):
    """True for excerpt files that are only mathpix figure references (vault conversion debris)."""
    return "mathpix" in file_name or text.lstrip().startswith("!(")
def clean_excerpt_text(text):
    """Strip the trailing #L3 tag and collapse whitespace."""
    text = re.sub(r"#L\d\s*$", "", text)
    return re.sub(r"\s+", " ", text).strip()
def load_well(repo_root, diagnostics):
    """Walk the vault -> list of category dicts:
    {label, path, claims: [{text, path, excerpts: [{source_ref, text, path}]}]}.
    Categories and claims sorted by label/text; excerpts sorted by file name (determinism).
    Returns [] (with a diagnostic) when the vault is not fetched locally."""
    root = os.path.join(repo_root, WELL_ROOT)
    if not os.path.isdir(root):
        diagnostics.append("MISSING LOCAL FOLDER (run fetch): " + WELL_ROOT)
        return []
    categories = []
    for cat_name in sorted(os.listdir(root)):
        cat_dir = os.path.join(root, cat_name)
        if not os.path.isdir(cat_dir):
            continue
        claims = []
        for claim_name in sorted(os.listdir(cat_dir)):
            claim_dir = os.path.join(cat_dir, claim_name)
            if not os.path.isdir(claim_dir):
                continue
            excerpts = []
            for file_name in sorted(os.listdir(claim_dir)):
                if not file_name.endswith(".md"):
                    continue
                if file_name[:-3] == claim_name:
                    continue
                rel_path = "%s/%s/%s/%s" % (WELL_ROOT, cat_name, claim_name, file_name)
                with open(os.path.join(claim_dir, file_name), encoding="utf-8") as f:
                    text = f.read()
                if is_image_artifact(file_name, text):
                    diagnostics.append("well: skipped image-artifact excerpt: " + rel_path)
                    continue
                m = SOURCE_PREFIX_RE.match(text.strip())
                if m:
                    source_ref, body = m.group(1).strip(), m.group(2)
                else:
                    source_ref, body = None, text
                    diagnostics.append("well: excerpt without source prefix: " + rel_path)
                excerpts.append({"source_ref": source_ref, "text": clean_excerpt_text(body), "path": rel_path})
            claims.append({"text": claim_name, "path": "%s/%s/%s" % (WELL_ROOT, cat_name, claim_name), "excerpts": excerpts})
        categories.append({"label": cat_name, "path": "%s/%s" % (WELL_ROOT, cat_name), "claims": claims})
    return categories
def resolve_source_ref(source_ref, works_by_base, chapters_by_key, works_by_date=None):
    """Resolve an excerpt's source attribution to node ids.
    Returns (work_id, chapter_id): chapter refs ('Chapter N - Title.md') match chapter nodes
    by (number, slugified title); other refs match works by base name (suffix-stripped),
    falling back to date + title-token fuzzy matching (the vault predates corpus renames).
    Either may be None when unresolved."""
    from . import ids
    from . import inventory
    if not source_ref:
        return None, None
    stem = source_ref[:-3] if source_ref.endswith(".md") else source_ref
    m = re.match(r"^Chapter (\d+) ?- ?(.+)$", stem)
    if m:
        key = (int(m.group(1)), ids.slugify(m.group(2)))
        ch = chapters_by_key.get(key)
        if ch:
            return ch["book"], ch["id"]
        return None, None
    base, _ = ids.split_base_name(source_ref)
    work = works_by_base.get(base)
    if work:
        return work["id"], None
    if works_by_date is not None:
        date = ids.date_from_base_name(base)
        tokens = inventory.normalize_title_tokens(base)
        best, best_sim = None, 0.0
        for cand in works_by_date.get(date, []):
            sim = inventory.jaccard(tokens, inventory.normalize_title_tokens(cand["base_name"]))
            if sim > best_sim:
                best, best_sim = cand, sim
        if best is not None and best_sim >= 0.5:
            return best["id"], None
    return None, None
