#!/usr/bin/env node
// Pre-generate OpenAI TTS clips for every line an applet can speak, and write
// the manifest module the runtime uses to know which clips exist.
//
// Usage:  OPENAI_API_KEY=... node scripts/generate-tts.js [--applet <name>] [--force]
// Clips:  public/audio/<applet>/<utteranceId>.mp3  (gitignored; canonical copy on [S3-FILES-BUCKET])
// Manifest: src/lib/<applet>-audio-manifest.js  (tracked — commit after regenerate)
//
// After changing spoken lines: sync copy if needed, run this script, then from repo root:
//   .venv/bin/python3 core/s3_archive.py refresh --area focusonfoundations_applet-audio --execute
//   .venv/bin/python3 core/s3_archive.py upload --area focusonfoundations_applet-audio --execute
// Commit the updated manifest JSONL only — not the mp3 files.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { utteranceId } from '../src/lib/utterance-id.js';

const APPLETS = {
  'counting-creatures': '../src/lib/counting-creatures.js',
  'logic-gates': '../src/lib/logic-gates.js',
};

const args = process.argv.slice(2);
const force = args.includes('--force');
const appletIdx = args.indexOf('--applet');
const applet = appletIdx !== -1 ? args[appletIdx + 1] : 'counting-creatures';
if (!APPLETS[applet]) {
  console.error(`Unknown applet "${applet}". Known: ${Object.keys(APPLETS).join(', ')}`);
  process.exit(1);
}
const { allUtterances } = await import(APPLETS[applet]);

const webRoot = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const outDir = path.join(webRoot, 'public', 'audio', applet);
const manifestPath = path.join(webRoot, 'src', 'lib', `${applet}-audio-manifest.js`);

const MODEL = 'gpt-4o-mini-tts';
const VOICE = 'nova';
const INSTRUCTIONS = 'A warm, cheerful teacher speaking to a young child. Slow, clear, playful, and encouraging. Short numbers and digit sequences are read slowly with a tiny pause between words.';

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error('OPENAI_API_KEY is required.');
  process.exit(1);
}

async function generateClip(text, filePath) {
  const res = await fetch('https://api.openai.com/v1/audio/speech', {
    method: 'POST',
    headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: MODEL, voice: VOICE, input: text, instructions: INSTRUCTIONS, response_format: 'mp3' }),
  });
  if (!res.ok) throw new Error(`TTS API ${res.status}: ${(await res.text()).slice(0, 300)}`);
  fs.writeFileSync(filePath, Buffer.from(await res.arrayBuffer()));
}

fs.mkdirSync(outDir, { recursive: true });
const texts = allUtterances();
console.log(`${applet}: ${texts.length} utterances; output: ${outDir}`);
let generated = 0, skipped = 0, failed = 0;
for (const text of texts) {
  const id = utteranceId(text);
  const filePath = path.join(outDir, `${id}.mp3`);
  if (!force && fs.existsSync(filePath) && fs.statSync(filePath).size > 0) { skipped++; continue; }
  try {
    await generateClip(text, filePath);
    generated++;
    console.log(`  ok  ${id}  "${text}"`);
  } catch (err) {
    failed++;
    console.error(`  FAIL  "${text}" — ${err.message}`);
  }
}

const presentIds = texts.map(utteranceId).filter((id) => {
  const p = path.join(outDir, `${id}.mp3`);
  return fs.existsSync(p) && fs.statSync(p).size > 0;
}).sort();
const banner = '// GENERATED by scripts/generate-tts.js — do not edit by hand.\n';
fs.writeFileSync(manifestPath, `${banner}export const AUDIO_CLIP_IDS = ${JSON.stringify(presentIds, null, 2)};\n`);
console.log(`generated ${generated}, skipped ${skipped}, failed ${failed}; manifest lists ${presentIds.length}/${texts.length} clips.`);
if (failed > 0) process.exit(1);
